/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.illumina.interop;

public final class bar_plot_options {
  public final static bar_plot_options Centered = new bar_plot_options("Centered");
  public final static bar_plot_options Shifted = new bar_plot_options("Shifted");
  public final static bar_plot_options UnknownBarPlotOption = new bar_plot_options("UnknownBarPlotOption", interop_runJNI.UnknownBarPlotOption_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static bar_plot_options swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + bar_plot_options.class + " with value " + swigValue);
  }

  private bar_plot_options(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private bar_plot_options(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private bar_plot_options(String swigName, bar_plot_options swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static bar_plot_options[] swigValues = { Centered, Shifted, UnknownBarPlotOption };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

