/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.illumina.interop;

public class base_event_metric extends base_cycle_metric {
  private transient long swigCPtr;

  protected base_event_metric(long cPtr, boolean cMemoryOwn) {
    super(interop_metricsJNI.base_event_metric_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(base_event_metric obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        interop_metricsJNI.delete_base_event_metric(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public base_event_metric(long lane, long tile, long cycle, event_type event_type) {
    this(interop_metricsJNI.new_base_event_metric__SWIG_0(lane, tile, cycle, event_type.swigValue()), true);
  }

  public base_event_metric(long lane, long tile, long cycle) {
    this(interop_metricsJNI.new_base_event_metric__SWIG_1(lane, tile, cycle), true);
  }

  public base_event_metric(long lane, long tile) {
    this(interop_metricsJNI.new_base_event_metric__SWIG_2(lane, tile), true);
  }

  public base_event_metric(long lane) {
    this(interop_metricsJNI.new_base_event_metric__SWIG_3(lane), true);
  }

  public base_event_metric() {
    this(interop_metricsJNI.new_base_event_metric__SWIG_4(), true);
  }

  public void set_base(long lane, long tile) {
    interop_metricsJNI.base_event_metric_set_base__SWIG_0(swigCPtr, this, lane, tile);
  }

  public void set_base(long lane, long tile, long cycle, event_type event_type) {
    interop_metricsJNI.base_event_metric_set_base__SWIG_1(swigCPtr, this, lane, tile, cycle, event_type.swigValue());
  }

  public event_type event_type() {
    return event_type.swigToEnum(interop_metricsJNI.base_event_metric_event_type__SWIG_0(swigCPtr, this));
  }

  public java.math.BigInteger event_type_long() {
    return interop_metricsJNI.base_event_metric_event_type_long(swigCPtr, this);
  }

  public void event_type(event_type event_type) {
    interop_metricsJNI.base_event_metric_event_type__SWIG_1(swigCPtr, this, event_type.swigValue());
  }

  public java.math.BigInteger id() {
    return interop_metricsJNI.base_event_metric_id(swigCPtr, this);
  }

  public static java.math.BigInteger create_id(java.math.BigInteger lane, java.math.BigInteger tile, java.math.BigInteger cycle, java.math.BigInteger event_type) {
    return interop_metricsJNI.base_event_metric_create_id(lane, tile, cycle, event_type);
  }

}
