/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.illumina.interop;

public class csharp_date_time {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected csharp_date_time(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(csharp_date_time obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        interop_metricsJNI.delete_csharp_date_time(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public csharp_date_time(java.math.BigInteger v) {
    this(interop_metricsJNI.new_csharp_date_time__SWIG_0(v), true);
  }

  public csharp_date_time() {
    this(interop_metricsJNI.new_csharp_date_time__SWIG_1(), true);
  }

  public java.math.BigInteger to_unix() {
    return interop_metricsJNI.csharp_date_time_to_unix__SWIG_0(swigCPtr, this);
  }

  public double to_seconds() {
    return interop_metricsJNI.csharp_date_time_to_seconds__SWIG_0(swigCPtr, this);
  }

  public static java.math.BigInteger to_unix(java.math.BigInteger val) {
    return interop_metricsJNI.csharp_date_time_to_unix__SWIG_1(val);
  }

  public static double to_seconds(java.math.BigInteger val) {
    return interop_metricsJNI.csharp_date_time_to_seconds__SWIG_1(val);
  }

  public static csharp_date_time to_csharp(java.math.BigInteger uval) {
    return new csharp_date_time(interop_metricsJNI.csharp_date_time_to_csharp(uval), true);
  }

  public void setValue(java.math.BigInteger value) {
    interop_metricsJNI.csharp_date_time_value_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getValue() {
    return interop_metricsJNI.csharp_date_time_value_get(swigCPtr, this);
  }

  public java.math.BigInteger to_int() {
    return interop_metricsJNI.csharp_date_time_to_int(swigCPtr, this);
  }

  public java.math.BigInteger to_binary() {
    return interop_metricsJNI.csharp_date_time_to_binary(swigCPtr, this);
  }

  public boolean equals(csharp_date_time other) {
    return interop_metricsJNI.csharp_date_time_equals(swigCPtr, this, csharp_date_time.getCPtr(other), other);
  }

}
