/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.illumina.interop;

public class event_metric_map {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected event_metric_map(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(event_metric_map obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        interop_metricsJNI.delete_event_metric_map(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public event_metric_map() {
    this(interop_metricsJNI.new_event_metric_map__SWIG_0(), true);
  }

  public event_metric_map(event_metric_map arg0) {
    this(interop_metricsJNI.new_event_metric_map__SWIG_1(event_metric_map.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return interop_metricsJNI.event_metric_map_size(swigCPtr, this);
  }

  public boolean empty() {
    return interop_metricsJNI.event_metric_map_empty(swigCPtr, this);
  }

  public void clear() {
    interop_metricsJNI.event_metric_map_clear(swigCPtr, this);
  }

  public event_metric get(java.math.BigInteger key) {
    return new event_metric(interop_metricsJNI.event_metric_map_get(swigCPtr, this, key), false);
  }

  public void set(java.math.BigInteger key, event_metric x) {
    interop_metricsJNI.event_metric_map_set(swigCPtr, this, key, event_metric.getCPtr(x), x);
  }

  public void del(java.math.BigInteger key) {
    interop_metricsJNI.event_metric_map_del(swigCPtr, this, key);
  }

  public boolean has_key(java.math.BigInteger key) {
    return interop_metricsJNI.event_metric_map_has_key(swigCPtr, this, key);
  }

}
