/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.illumina.interop;

public class event_table_id_less {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected event_table_id_less(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(event_table_id_less obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        interop_tableJNI.delete_event_table_id_less(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public event_table_id_less(event_table table) {
    this(interop_tableJNI.new_event_table_id_less(event_table.getCPtr(table), table), true);
  }

}
