/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.illumina.interop;

public class fwhm_grid_metric_header extends base_cycle_metric_header {
  private transient long swigCPtr;

  protected fwhm_grid_metric_header(long cPtr, boolean cMemoryOwn) {
    super(interop_metricsJNI.fwhm_grid_metric_header_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fwhm_grid_metric_header obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        interop_metricsJNI.delete_fwhm_grid_metric_header(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public fwhm_grid_metric_header(int num_bins_x, int num_bins_y, int channel_count) {
    this(interop_metricsJNI.new_fwhm_grid_metric_header(num_bins_x, num_bins_y, channel_count), true);
  }

  public int num_bins_x() {
    return interop_metricsJNI.fwhm_grid_metric_header_num_bins_x(swigCPtr, this);
  }

  public int num_bins_y() {
    return interop_metricsJNI.fwhm_grid_metric_header_num_bins_y(swigCPtr, this);
  }

  public int channel_count() {
    return interop_metricsJNI.fwhm_grid_metric_header_channel_count(swigCPtr, this);
  }

  public static fwhm_grid_metric_header default_header() {
    return new fwhm_grid_metric_header(interop_metricsJNI.fwhm_grid_metric_header_default_header(), true);
  }

  public void clear() {
    interop_metricsJNI.fwhm_grid_metric_header_clear(swigCPtr, this);
  }

}
