/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.illumina.interop;

public class image_dimensions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected image_dimensions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(image_dimensions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        interop_runJNI.delete_image_dimensions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public image_dimensions(long width, long height) {
    this(interop_runJNI.new_image_dimensions__SWIG_0(width, height), true);
  }

  public image_dimensions(long width) {
    this(interop_runJNI.new_image_dimensions__SWIG_1(width), true);
  }

  public image_dimensions() {
    this(interop_runJNI.new_image_dimensions__SWIG_2(), true);
  }

  public long width() {
    return interop_runJNI.image_dimensions_width(swigCPtr, this);
  }

  public long height() {
    return interop_runJNI.image_dimensions_height(swigCPtr, this);
  }

}
