/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.illumina.interop;

public class index_count_summary {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected index_count_summary(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(index_count_summary obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        interop_summaryJNI.delete_index_count_summary(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public index_count_summary(long id, String index1, String index2, String sample_id, String project_name, java.math.BigInteger count, float fraction_mapped) {
    this(interop_summaryJNI.new_index_count_summary__SWIG_0(id, index1, index2, sample_id, project_name, count, fraction_mapped), true);
  }

  public index_count_summary(long id, String index1, String index2, String sample_id, String project_name, java.math.BigInteger count) {
    this(interop_summaryJNI.new_index_count_summary__SWIG_1(id, index1, index2, sample_id, project_name, count), true);
  }

  public index_count_summary(long id, String index1, String index2, String sample_id, String project_name) {
    this(interop_summaryJNI.new_index_count_summary__SWIG_2(id, index1, index2, sample_id, project_name), true);
  }

  public index_count_summary(long id, String index1, String index2, String sample_id) {
    this(interop_summaryJNI.new_index_count_summary__SWIG_3(id, index1, index2, sample_id), true);
  }

  public index_count_summary(long id, String index1, String index2) {
    this(interop_summaryJNI.new_index_count_summary__SWIG_4(id, index1, index2), true);
  }

  public index_count_summary(long id, String index1) {
    this(interop_summaryJNI.new_index_count_summary__SWIG_5(id, index1), true);
  }

  public index_count_summary(long id) {
    this(interop_summaryJNI.new_index_count_summary__SWIG_6(id), true);
  }

  public index_count_summary() {
    this(interop_summaryJNI.new_index_count_summary__SWIG_7(), true);
  }

  public long id() {
    return interop_summaryJNI.index_count_summary_id__SWIG_0(swigCPtr, this);
  }

  public void id(long n) {
    interop_summaryJNI.index_count_summary_id__SWIG_1(swigCPtr, this, n);
  }

  public String index1() {
    return interop_summaryJNI.index_count_summary_index1(swigCPtr, this);
  }

  public String index2() {
    return interop_summaryJNI.index_count_summary_index2(swigCPtr, this);
  }

  public float fraction_mapped() {
    return interop_summaryJNI.index_count_summary_fraction_mapped(swigCPtr, this);
  }

  public java.math.BigInteger cluster_count() {
    return interop_summaryJNI.index_count_summary_cluster_count(swigCPtr, this);
  }

  public String sample_id() {
    return interop_summaryJNI.index_count_summary_sample_id(swigCPtr, this);
  }

  public String project_name() {
    return interop_summaryJNI.index_count_summary_project_name(swigCPtr, this);
  }

  public index_count_summary add(java.math.BigInteger cluster_count) {
    return new index_count_summary(interop_summaryJNI.index_count_summary_add(swigCPtr, this, cluster_count), false);
  }

  public void update_fraction_mapped(double total_pf_cluster_count) {
    interop_summaryJNI.index_count_summary_update_fraction_mapped(swigCPtr, this, total_pf_cluster_count);
  }

  public boolean is_less(index_count_summary rhs) {
    return interop_summaryJNI.index_count_summary_is_less(swigCPtr, this, index_count_summary.getCPtr(rhs), rhs);
  }

}
