/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.illumina.interop;

public class index_lane_summary {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected index_lane_summary(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(index_lane_summary obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        interop_summaryJNI.delete_index_lane_summary(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public index_lane_summary(java.math.BigInteger total_reads, java.math.BigInteger total_pf_reads, float total_fraction_mapped_reads, float mapped_reads_cv, float min_mapped_reads, float max_mapped_reads) {
    this(interop_summaryJNI.new_index_lane_summary__SWIG_0(total_reads, total_pf_reads, total_fraction_mapped_reads, mapped_reads_cv, min_mapped_reads, max_mapped_reads), true);
  }

  public index_lane_summary(java.math.BigInteger total_reads, java.math.BigInteger total_pf_reads, float total_fraction_mapped_reads, float mapped_reads_cv, float min_mapped_reads) {
    this(interop_summaryJNI.new_index_lane_summary__SWIG_1(total_reads, total_pf_reads, total_fraction_mapped_reads, mapped_reads_cv, min_mapped_reads), true);
  }

  public index_lane_summary(java.math.BigInteger total_reads, java.math.BigInteger total_pf_reads, float total_fraction_mapped_reads, float mapped_reads_cv) {
    this(interop_summaryJNI.new_index_lane_summary__SWIG_2(total_reads, total_pf_reads, total_fraction_mapped_reads, mapped_reads_cv), true);
  }

  public index_lane_summary(java.math.BigInteger total_reads, java.math.BigInteger total_pf_reads, float total_fraction_mapped_reads) {
    this(interop_summaryJNI.new_index_lane_summary__SWIG_3(total_reads, total_pf_reads, total_fraction_mapped_reads), true);
  }

  public index_lane_summary(java.math.BigInteger total_reads, java.math.BigInteger total_pf_reads) {
    this(interop_summaryJNI.new_index_lane_summary__SWIG_4(total_reads, total_pf_reads), true);
  }

  public index_lane_summary(java.math.BigInteger total_reads) {
    this(interop_summaryJNI.new_index_lane_summary__SWIG_5(total_reads), true);
  }

  public index_lane_summary() {
    this(interop_summaryJNI.new_index_lane_summary__SWIG_6(), true);
  }

  public void resize(long n) {
    interop_summaryJNI.index_lane_summary_resize(swigCPtr, this, n);
  }

  public void reserve(long n) {
    interop_summaryJNI.index_lane_summary_reserve(swigCPtr, this, n);
  }

  public void push_back(index_count_summary count_summary) {
    interop_summaryJNI.index_lane_summary_push_back(swigCPtr, this, index_count_summary.getCPtr(count_summary), count_summary);
  }

  public index_count_summary at(long n) throws index_out_of_bounds_exception {
    return new index_count_summary(interop_summaryJNI.index_lane_summary_at(swigCPtr, this, n), false);
  }

  public long size() {
    return interop_summaryJNI.index_lane_summary_size(swigCPtr, this);
  }

  public java.math.BigInteger total_reads() {
    return interop_summaryJNI.index_lane_summary_total_reads(swigCPtr, this);
  }

  public java.math.BigInteger total_pf_reads() {
    return interop_summaryJNI.index_lane_summary_total_pf_reads(swigCPtr, this);
  }

  public float total_fraction_mapped_reads() {
    return interop_summaryJNI.index_lane_summary_total_fraction_mapped_reads(swigCPtr, this);
  }

  public float mapped_reads_cv() {
    return interop_summaryJNI.index_lane_summary_mapped_reads_cv(swigCPtr, this);
  }

  public float min_mapped_reads() {
    return interop_summaryJNI.index_lane_summary_min_mapped_reads(swigCPtr, this);
  }

  public float max_mapped_reads() {
    return interop_summaryJNI.index_lane_summary_max_mapped_reads(swigCPtr, this);
  }

  public void sort() {
    interop_summaryJNI.index_lane_summary_sort(swigCPtr, this);
  }

  public void set(java.math.BigInteger total_mapped_reads, java.math.BigInteger pf_cluster_count_total, java.math.BigInteger cluster_count_total, float min_fraction_mapped, float max_fraction_mapped, float cv_fraction_mapped) {
    interop_summaryJNI.index_lane_summary_set(swigCPtr, this, total_mapped_reads, pf_cluster_count_total, cluster_count_total, min_fraction_mapped, max_fraction_mapped, cv_fraction_mapped);
  }

  public void clear() {
    interop_summaryJNI.index_lane_summary_clear(swigCPtr, this);
  }

}
