/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.illumina.interop;

public class invalid_argument extends base_exception {
  private transient long swigCPtr;

  protected invalid_argument(long cPtr, boolean cMemoryOwn) {
    super(interop_commJNI.invalid_argument_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(invalid_argument obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        interop_commJNI.delete_invalid_argument(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public invalid_argument(String mesg) {
    this(interop_commJNI.new_invalid_argument(mesg), true);
  }

}
