/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.illumina.interop;

public class lane_summary_vector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected lane_summary_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(lane_summary_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        interop_summaryJNI.delete_lane_summary_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public lane_summary_vector() {
    this(interop_summaryJNI.new_lane_summary_vector__SWIG_0(), true);
  }

  public lane_summary_vector(long n) {
    this(interop_summaryJNI.new_lane_summary_vector__SWIG_1(n), true);
  }

  public long size() {
    return interop_summaryJNI.lane_summary_vector_size(swigCPtr, this);
  }

  public long capacity() {
    return interop_summaryJNI.lane_summary_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    interop_summaryJNI.lane_summary_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return interop_summaryJNI.lane_summary_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    interop_summaryJNI.lane_summary_vector_clear(swigCPtr, this);
  }

  public void add(lane_summary x) {
    interop_summaryJNI.lane_summary_vector_add(swigCPtr, this, lane_summary.getCPtr(x), x);
  }

  public lane_summary get(int i) {
    return new lane_summary(interop_summaryJNI.lane_summary_vector_get(swigCPtr, this, i), false);
  }

  public void set(int i, lane_summary val) {
    interop_summaryJNI.lane_summary_vector_set(swigCPtr, this, i, lane_summary.getCPtr(val), val);
  }

}
