/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.illumina.interop;

public class run_diagnostics_metric extends base_cycle_metric {
  private transient long swigCPtr;

  protected run_diagnostics_metric(long cPtr, boolean cMemoryOwn) {
    super(interop_metricsJNI.run_diagnostics_metric_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(run_diagnostics_metric obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        interop_metricsJNI.delete_run_diagnostics_metric(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public run_diagnostics_metric() {
    this(interop_metricsJNI.new_run_diagnostics_metric__SWIG_0(), true);
  }

  public run_diagnostics_metric(long lane, long tile, long cycle) {
    this(interop_metricsJNI.new_run_diagnostics_metric__SWIG_1(lane, tile, cycle), true);
  }

  public run_diagnostics_metric(base_cycle_metric_header arg0) {
    this(interop_metricsJNI.new_run_diagnostics_metric__SWIG_2(base_cycle_metric_header.getCPtr(arg0), arg0), true);
  }

  public void blank_image(boolean flag) {
    interop_metricsJNI.run_diagnostics_metric_blank_image(swigCPtr, this, flag);
  }

  public void dead_tile(boolean flag) {
    interop_metricsJNI.run_diagnostics_metric_dead_tile(swigCPtr, this, flag);
  }

  public void failed_tile_cycle(boolean flag) {
    interop_metricsJNI.run_diagnostics_metric_failed_tile_cycle(swigCPtr, this, flag);
  }

  public void q_outlier(boolean flag) {
    interop_metricsJNI.run_diagnostics_metric_q_outlier(swigCPtr, this, flag);
  }

  public uint_vector get_issues_for_entry() {
    return new uint_vector(interop_metricsJNI.run_diagnostics_metric_get_issues_for_entry(swigCPtr, this), false);
  }

  public long get_issue(long type_index) {
    return interop_metricsJNI.run_diagnostics_metric_get_issue(swigCPtr, this, type_index);
  }

  public static String prefix() {
    return interop_metricsJNI.run_diagnostics_metric_prefix();
  }

  public final static int TYPE = interop_metricsJNI.run_diagnostics_metric_TYPE_get();
  public final static int LATEST_VERSION = interop_metricsJNI.run_diagnostics_metric_LATEST_VERSION_get();

}
