/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.illumina.interop;

public final class surface_type {
  public final static surface_type SentinelSurface = new surface_type("SentinelSurface");
  public final static surface_type Top = new surface_type("Top");
  public final static surface_type Bottom = new surface_type("Bottom");
  public final static surface_type UnknownSurface = new surface_type("UnknownSurface", interop_runJNI.UnknownSurface_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static surface_type swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + surface_type.class + " with value " + swigValue);
  }

  private surface_type(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private surface_type(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private surface_type(String swigName, surface_type swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static surface_type[] swigValues = { SentinelSurface, Top, Bottom, UnknownSurface };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

