/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.illumina.interop;

public class ushort_vector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ushort_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ushort_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        interop_runJNI.delete_ushort_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ushort_vector() {
    this(interop_runJNI.new_ushort_vector__SWIG_0(), true);
  }

  public ushort_vector(long n) {
    this(interop_runJNI.new_ushort_vector__SWIG_1(n), true);
  }

  public long size() {
    return interop_runJNI.ushort_vector_size(swigCPtr, this);
  }

  public long capacity() {
    return interop_runJNI.ushort_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    interop_runJNI.ushort_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return interop_runJNI.ushort_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    interop_runJNI.ushort_vector_clear(swigCPtr, this);
  }

  public void add(int x) {
    interop_runJNI.ushort_vector_add(swigCPtr, this, x);
  }

  public int get(int i) {
    return interop_runJNI.ushort_vector_get(swigCPtr, this, i);
  }

  public void set(int i, int val) {
    interop_runJNI.ushort_vector_set(swigCPtr, this, i, val);
  }

}
