//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Illumina.InterOp.RunMetrics {

using Illumina.InterOp.Metrics;
using Illumina.InterOp.Run;
using Illumina.InterOp.Comm;

class c_csharp_run_metricsPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="SWIGRegisterExceptionCallbacks_c_csharp_run_metrics")]
    public static extern void SWIGRegisterExceptionCallbacks_c_csharp_run_metrics(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_c_csharp_run_metrics")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_c_csharp_run_metrics(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_c_csharp_run_metrics(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_c_csharp_run_metrics(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(c_csharp_run_metricsPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(c_csharp_run_metricsPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="SWIGRegisterStringCallback_c_csharp_run_metrics")]
    public static extern void SWIGRegisterStringCallback_c_csharp_run_metrics(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_c_csharp_run_metrics(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static c_csharp_run_metricsPINVOKE() {
  }


  class CustomExceptionHelper_base_exception {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="ImportCustomExceptionRegisterCallback_base_exception")]
    public static extern
           void ImportCustomExceptionRegisterCallback_base_exception(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new base_exception(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_base_exception() {
      ImportCustomExceptionRegisterCallback_base_exception(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_base_exception exceptionHelper_base_exception = new CustomExceptionHelper_base_exception();
#pragma warning restore 0414


  class CustomExceptionHelper_xml_file_not_found_exception {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="ImportCustomExceptionRegisterCallback_xml_file_not_found_exception")]
    public static extern
           void ImportCustomExceptionRegisterCallback_xml_file_not_found_exception(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new xml_file_not_found_exception(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_xml_file_not_found_exception() {
      ImportCustomExceptionRegisterCallback_xml_file_not_found_exception(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_xml_file_not_found_exception exceptionHelper_xml_file_not_found_exception = new CustomExceptionHelper_xml_file_not_found_exception();
#pragma warning restore 0414


  class CustomExceptionHelper_xml_format_exception {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="ImportCustomExceptionRegisterCallback_xml_format_exception")]
    public static extern
           void ImportCustomExceptionRegisterCallback_xml_format_exception(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new xml_format_exception(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_xml_format_exception() {
      ImportCustomExceptionRegisterCallback_xml_format_exception(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_xml_format_exception exceptionHelper_xml_format_exception = new CustomExceptionHelper_xml_format_exception();
#pragma warning restore 0414


  class CustomExceptionHelper_xml_parse_exception {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="ImportCustomExceptionRegisterCallback_xml_parse_exception")]
    public static extern
           void ImportCustomExceptionRegisterCallback_xml_parse_exception(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new xml_parse_exception(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_xml_parse_exception() {
      ImportCustomExceptionRegisterCallback_xml_parse_exception(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_xml_parse_exception exceptionHelper_xml_parse_exception = new CustomExceptionHelper_xml_parse_exception();
#pragma warning restore 0414


  class CustomExceptionHelper_bad_xml_format_exception {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="ImportCustomExceptionRegisterCallback_bad_xml_format_exception")]
    public static extern
           void ImportCustomExceptionRegisterCallback_bad_xml_format_exception(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new bad_xml_format_exception(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_bad_xml_format_exception() {
      ImportCustomExceptionRegisterCallback_bad_xml_format_exception(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_bad_xml_format_exception exceptionHelper_bad_xml_format_exception = new CustomExceptionHelper_bad_xml_format_exception();
#pragma warning restore 0414


  class CustomExceptionHelper_empty_xml_format_exception {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="ImportCustomExceptionRegisterCallback_empty_xml_format_exception")]
    public static extern
           void ImportCustomExceptionRegisterCallback_empty_xml_format_exception(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new empty_xml_format_exception(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_empty_xml_format_exception() {
      ImportCustomExceptionRegisterCallback_empty_xml_format_exception(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_empty_xml_format_exception exceptionHelper_empty_xml_format_exception = new CustomExceptionHelper_empty_xml_format_exception();
#pragma warning restore 0414


  class CustomExceptionHelper_missing_xml_element_exception {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="ImportCustomExceptionRegisterCallback_missing_xml_element_exception")]
    public static extern
           void ImportCustomExceptionRegisterCallback_missing_xml_element_exception(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new missing_xml_element_exception(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_missing_xml_element_exception() {
      ImportCustomExceptionRegisterCallback_missing_xml_element_exception(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_missing_xml_element_exception exceptionHelper_missing_xml_element_exception = new CustomExceptionHelper_missing_xml_element_exception();
#pragma warning restore 0414


  class CustomExceptionHelper_invalid_read_exception {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="ImportCustomExceptionRegisterCallback_invalid_read_exception")]
    public static extern
           void ImportCustomExceptionRegisterCallback_invalid_read_exception(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new invalid_read_exception(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_invalid_read_exception() {
      ImportCustomExceptionRegisterCallback_invalid_read_exception(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_invalid_read_exception exceptionHelper_invalid_read_exception = new CustomExceptionHelper_invalid_read_exception();
#pragma warning restore 0414


  class CustomExceptionHelper_invalid_tile_naming_method {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="ImportCustomExceptionRegisterCallback_invalid_tile_naming_method")]
    public static extern
           void ImportCustomExceptionRegisterCallback_invalid_tile_naming_method(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new invalid_tile_naming_method(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_invalid_tile_naming_method() {
      ImportCustomExceptionRegisterCallback_invalid_tile_naming_method(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_invalid_tile_naming_method exceptionHelper_invalid_tile_naming_method = new CustomExceptionHelper_invalid_tile_naming_method();
#pragma warning restore 0414


  class CustomExceptionHelper_invalid_run_info_exception {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="ImportCustomExceptionRegisterCallback_invalid_run_info_exception")]
    public static extern
           void ImportCustomExceptionRegisterCallback_invalid_run_info_exception(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new invalid_run_info_exception(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_invalid_run_info_exception() {
      ImportCustomExceptionRegisterCallback_invalid_run_info_exception(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_invalid_run_info_exception exceptionHelper_invalid_run_info_exception = new CustomExceptionHelper_invalid_run_info_exception();
#pragma warning restore 0414


  class CustomExceptionHelper_invalid_run_info_cycle_exception {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="ImportCustomExceptionRegisterCallback_invalid_run_info_cycle_exception")]
    public static extern
           void ImportCustomExceptionRegisterCallback_invalid_run_info_cycle_exception(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new invalid_run_info_cycle_exception(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_invalid_run_info_cycle_exception() {
      ImportCustomExceptionRegisterCallback_invalid_run_info_cycle_exception(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_invalid_run_info_cycle_exception exceptionHelper_invalid_run_info_cycle_exception = new CustomExceptionHelper_invalid_run_info_cycle_exception();
#pragma warning restore 0414


  class CustomExceptionHelper_invalid_tile_list_exception {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="ImportCustomExceptionRegisterCallback_invalid_tile_list_exception")]
    public static extern
           void ImportCustomExceptionRegisterCallback_invalid_tile_list_exception(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new invalid_tile_list_exception(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_invalid_tile_list_exception() {
      ImportCustomExceptionRegisterCallback_invalid_tile_list_exception(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_invalid_tile_list_exception exceptionHelper_invalid_tile_list_exception = new CustomExceptionHelper_invalid_tile_list_exception();
#pragma warning restore 0414


  class CustomExceptionHelper_file_not_found_exception {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="ImportCustomExceptionRegisterCallback_file_not_found_exception")]
    public static extern
           void ImportCustomExceptionRegisterCallback_file_not_found_exception(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new file_not_found_exception(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_file_not_found_exception() {
      ImportCustomExceptionRegisterCallback_file_not_found_exception(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_file_not_found_exception exceptionHelper_file_not_found_exception = new CustomExceptionHelper_file_not_found_exception();
#pragma warning restore 0414


  class CustomExceptionHelper_format_exception {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="ImportCustomExceptionRegisterCallback_format_exception")]
    public static extern
           void ImportCustomExceptionRegisterCallback_format_exception(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new format_exception(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_format_exception() {
      ImportCustomExceptionRegisterCallback_format_exception(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_format_exception exceptionHelper_format_exception = new CustomExceptionHelper_format_exception();
#pragma warning restore 0414


  class CustomExceptionHelper_bad_format_exception {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="ImportCustomExceptionRegisterCallback_bad_format_exception")]
    public static extern
           void ImportCustomExceptionRegisterCallback_bad_format_exception(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new bad_format_exception(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_bad_format_exception() {
      ImportCustomExceptionRegisterCallback_bad_format_exception(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_bad_format_exception exceptionHelper_bad_format_exception = new CustomExceptionHelper_bad_format_exception();
#pragma warning restore 0414


  class CustomExceptionHelper_incomplete_file_exception {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="ImportCustomExceptionRegisterCallback_incomplete_file_exception")]
    public static extern
           void ImportCustomExceptionRegisterCallback_incomplete_file_exception(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new incomplete_file_exception(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_incomplete_file_exception() {
      ImportCustomExceptionRegisterCallback_incomplete_file_exception(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_incomplete_file_exception exceptionHelper_incomplete_file_exception = new CustomExceptionHelper_incomplete_file_exception();
#pragma warning restore 0414


  class CustomExceptionHelper_invalid_argument {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="ImportCustomExceptionRegisterCallback_invalid_argument")]
    public static extern
           void ImportCustomExceptionRegisterCallback_invalid_argument(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new invalid_argument(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_invalid_argument() {
      ImportCustomExceptionRegisterCallback_invalid_argument(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_invalid_argument exceptionHelper_invalid_argument = new CustomExceptionHelper_invalid_argument();
#pragma warning restore 0414


  class CustomExceptionHelper_index_out_of_bounds_exception {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="ImportCustomExceptionRegisterCallback_index_out_of_bounds_exception")]
    public static extern
           void ImportCustomExceptionRegisterCallback_index_out_of_bounds_exception(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new index_out_of_bounds_exception(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_index_out_of_bounds_exception() {
      ImportCustomExceptionRegisterCallback_index_out_of_bounds_exception(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_index_out_of_bounds_exception exceptionHelper_index_out_of_bounds_exception = new CustomExceptionHelper_index_out_of_bounds_exception();
#pragma warning restore 0414


  class CustomExceptionHelper_invalid_channel_exception {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CustomExceptionRegisterCallback_invalid_channel_exception")]
    public static extern
           void CustomExceptionRegisterCallback_invalid_channel_exception(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new invalid_channel_exception(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_invalid_channel_exception() {
      CustomExceptionRegisterCallback_invalid_channel_exception(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_invalid_channel_exception exceptionHelper_invalid_channel_exception = new CustomExceptionHelper_invalid_channel_exception();
#pragma warning restore 0414


  class CustomExceptionHelper_invalid_metric_type {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CustomExceptionRegisterCallback_invalid_metric_type")]
    public static extern
           void CustomExceptionRegisterCallback_invalid_metric_type(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new invalid_metric_type(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_invalid_metric_type() {
      CustomExceptionRegisterCallback_invalid_metric_type(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_invalid_metric_type exceptionHelper_invalid_metric_type = new CustomExceptionHelper_invalid_metric_type();
#pragma warning restore 0414


  class CustomExceptionHelper_invalid_parameter {
    // C# delegate for the C/C++ customExceptionCallback
    public delegate void CustomExceptionDelegate(string message);
    static CustomExceptionDelegate customDelegate =
                                   new CustomExceptionDelegate(SetPendingCustomException);

    [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CustomExceptionRegisterCallback_invalid_parameter")]
    public static extern
           void CustomExceptionRegisterCallback_invalid_parameter(CustomExceptionDelegate customCallback);

    static void SetPendingCustomException(string message) {
      SWIGPendingException.Set(new invalid_parameter(message, SWIGPendingException.Retrieve()));
    }

    static CustomExceptionHelper_invalid_parameter() {
      CustomExceptionRegisterCallback_invalid_parameter(customDelegate);
    }
  }
#pragma warning disable 0414 // Need to keep a reference to this object
  static CustomExceptionHelper_invalid_parameter exceptionHelper_invalid_parameter = new CustomExceptionHelper_invalid_parameter();
#pragma warning restore 0414


  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_delete_invalid_channel_exception___")]
  public static extern void delete_invalid_channel_exception(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_delete_invalid_metric_type___")]
  public static extern void delete_invalid_metric_type(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_delete_invalid_parameter___")]
  public static extern void delete_invalid_parameter(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_copy_focus___")]
  public static extern void copy_focus(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.IntPtr jarg2, uint jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_count_q_metric_bins__SWIG_1___")]
  public static extern uint count_q_metric_bins__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_count_q_metric_bins__SWIG_2___")]
  public static extern uint count_q_metric_bins__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_count_q_metric_bins__SWIG_3___")]
  public static extern uint count_q_metric_bins__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_populate_cumulative_distribution__SWIG_0___")]
  public static extern void populate_cumulative_distribution__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_populate_cumulative_distribution__SWIG_1___")]
  public static extern void populate_cumulative_distribution__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_populate_cumulative_distribution__SWIG_2___")]
  public static extern void populate_cumulative_distribution__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_requires_legacy_bins___")]
  public static extern bool requires_legacy_bins(uint jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_populate_legacy_q_score_bins__SWIG_0___")]
  public static extern void populate_legacy_q_score_bins__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_compress_q_metrics__SWIG_0___")]
  public static extern void compress_q_metrics__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_compress_q_metrics__SWIG_1___")]
  public static extern void compress_q_metrics__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_populate_legacy_q_score_bins__SWIG_1___")]
  public static extern void populate_legacy_q_score_bins__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_populate_legacy_q_score_bins__SWIG_2___")]
  public static extern void populate_legacy_q_score_bins__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_count_qvals__SWIG_0___")]
  public static extern uint count_qvals__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_count_qvals__SWIG_1___")]
  public static extern uint count_qvals__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_count_qvals__SWIG_2___")]
  public static extern uint count_qvals__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_is_compressed__SWIG_0___")]
  public static extern bool is_compressed__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_is_compressed__SWIG_1___")]
  public static extern bool is_compressed__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_is_compressed__SWIG_2___")]
  public static extern bool is_compressed__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_max_qval__SWIG_0___")]
  public static extern uint max_qval__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_max_qval__SWIG_1___")]
  public static extern uint max_qval__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_max_qval__SWIG_2___")]
  public static extern uint max_qval__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_index_for_q_value__SWIG_0___")]
  public static extern uint index_for_q_value__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_index_for_q_value__SWIG_1___")]
  public static extern uint index_for_q_value__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_create_collapse_q_metrics___")]
  public static extern void create_collapse_q_metrics(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_create_q_metrics_by_lane___")]
  public static extern void create_q_metrics_by_lane(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_to_group___")]
  public static extern int to_group(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_to_description___")]
  public static extern string to_description(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_list_descriptions___")]
  public static extern void list_descriptions(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_to_feature__SWIG_0___")]
  public static extern int to_feature__SWIG_0(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_to_feature__SWIG_1___")]
  public static extern int to_feature__SWIG_1(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_is_base_metric___")]
  public static extern bool is_base_metric(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_is_channel_metric___")]
  public static extern bool is_channel_metric(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_is_read_metric___")]
  public static extern bool is_read_metric(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_is_cycle_metric___")]
  public static extern bool is_cycle_metric(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_is_tile_metric___")]
  public static extern bool is_tile_metric(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_to_feature__SWIG_2___")]
  public static extern int to_feature__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_is_subtile_metric___")]
  public static extern bool is_subtile_metric(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_is_interval_event___")]
  public static extern bool is_interval_event(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_is_iuo_metric___")]
  public static extern bool is_iuo_metric(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_is_iuo___")]
  public static extern bool is_iuo(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_list_metrics_to_load__SWIG_0___")]
  public static extern void list_metrics_to_load__SWIG_0(int jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_list_metrics_to_load__SWIG_1___")]
  public static extern void list_metrics_to_load__SWIG_1(int jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_list_metrics_to_load__SWIG_2___")]
  public static extern void list_metrics_to_load__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_list_metrics_to_load__SWIG_3___")]
  public static extern void list_metrics_to_load__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_list_metrics_to_load__SWIG_4___")]
  public static extern void list_metrics_to_load__SWIG_4(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_list_summary_metric_groups__SWIG_0___")]
  public static extern void list_summary_metric_groups__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_list_summary_metric_groups__SWIG_1___")]
  public static extern void list_summary_metric_groups__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_list_index_summary_metric_groups___")]
  public static extern void list_index_summary_metric_groups(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_list_summary_metrics_to_load__SWIG_0___")]
  public static extern void list_summary_metrics_to_load__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_list_summary_metrics_to_load__SWIG_1___")]
  public static extern void list_summary_metrics_to_load__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_list_summary_metrics_to_load__SWIG_2___")]
  public static extern void list_summary_metrics_to_load__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_list_index_metrics_to_load___")]
  public static extern void list_index_metrics_to_load(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_list_analysis_metrics_to_load__SWIG_0___")]
  public static extern void list_analysis_metrics_to_load__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_list_analysis_metrics_to_load__SWIG_1___")]
  public static extern void list_analysis_metrics_to_load__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_list_event_metrics_to_load___")]
  public static extern void list_event_metrics_to_load(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_list_subtile_metrics_to_load___")]
  public static extern void list_subtile_metrics_to_load(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_list_run_diagnostics_metrics_to_load___")]
  public static extern void list_run_diagnostics_metrics_to_load(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_list_run_diagnostics_metric_groups___")]
  public static extern void list_run_diagnostics_metric_groups(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_new_run_metrics__SWIG_0___")]
  public static extern global::System.IntPtr new_run_metrics__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_new_run_metrics__SWIG_1___")]
  public static extern global::System.IntPtr new_run_metrics__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_new_run_metrics__SWIG_2___")]
  public static extern global::System.IntPtr new_run_metrics__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_read__SWIG_0___")]
  public static extern void run_metrics_read__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_read__SWIG_1___")]
  public static extern void run_metrics_read__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_read__SWIG_2___")]
  public static extern void run_metrics_read__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, uint jarg4, bool jarg5);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_read__SWIG_3___")]
  public static extern void run_metrics_read__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_read__SWIG_4___")]
  public static extern void run_metrics_read__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_read_xml___")]
  public static extern uint run_metrics_read_xml(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_read_run_info___")]
  public static extern void run_metrics_read_run_info(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_read_run_parameters__SWIG_0___")]
  public static extern uint run_metrics_read_run_parameters__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_read_run_parameters__SWIG_1___")]
  public static extern uint run_metrics_read_run_parameters__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_finalize_after_load__SWIG_0___")]
  public static extern void run_metrics_finalize_after_load__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_finalize_after_load__SWIG_1___")]
  public static extern void run_metrics_finalize_after_load__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_empty___")]
  public static extern bool run_metrics_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_legacy_channel_update___")]
  public static extern void run_metrics_legacy_channel_update(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_naming_method___")]
  public static extern void run_metrics_set_naming_method(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_count_legacy_bins__SWIG_0___")]
  public static extern uint run_metrics_count_legacy_bins__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_count_legacy_bins__SWIG_1___")]
  public static extern uint run_metrics_count_legacy_bins__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_is_run_parameters_required__SWIG_0___")]
  public static extern bool run_metrics_is_run_parameters_required__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_is_run_parameters_required__SWIG_1___")]
  public static extern bool run_metrics_is_run_parameters_required__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_run_info__SWIG_0___")]
  public static extern global::System.IntPtr run_metrics_run_info__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_run_info__SWIG_1___")]
  public static extern void run_metrics_run_info__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_run_parameters__SWIG_0___")]
  public static extern global::System.IntPtr run_metrics_run_parameters__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_run_parameters__SWIG_1___")]
  public static extern void run_metrics_run_parameters__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_list_filenames__SWIG_0___")]
  public static extern void run_metrics_list_filenames__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, string jarg4, bool jarg5);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_list_filenames__SWIG_1___")]
  public static extern void run_metrics_list_filenames__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_list_filenames__SWIG_2___")]
  public static extern void run_metrics_list_filenames__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, bool jarg4, bool jarg5);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_list_filenames__SWIG_3___")]
  public static extern void run_metrics_list_filenames__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_list_filenames__SWIG_4___")]
  public static extern void run_metrics_list_filenames__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_check_for_data_sources___")]
  public static extern void run_metrics_check_for_data_sources(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_read_metrics__SWIG_0___")]
  public static extern void run_metrics_read_metrics__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, uint jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_read_metrics__SWIG_1___")]
  public static extern void run_metrics_read_metrics__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, uint jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, uint jarg5, bool jarg6);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_read_metrics__SWIG_2___")]
  public static extern void run_metrics_read_metrics__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, uint jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, uint jarg5);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_write_metrics__SWIG_0___")]
  public static extern void run_metrics_write_metrics__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_write_metrics__SWIG_1___")]
  public static extern void run_metrics_write_metrics__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_read_metrics_from_buffer___")]
  public static extern void run_metrics_read_metrics_from_buffer(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.IntPtr jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_write_metrics_to_buffer___")]
  public static extern void run_metrics_write_metrics_to_buffer(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.IntPtr jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_calculate_buffer_size___")]
  public static extern uint run_metrics_calculate_buffer_size(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_validate___")]
  public static extern void run_metrics_validate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_is_group_empty__SWIG_0___")]
  public static extern bool run_metrics_is_group_empty__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_is_group_empty__SWIG_1___")]
  public static extern bool run_metrics_is_group_empty__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_populate_id_map__SWIG_0___")]
  public static extern void run_metrics_populate_id_map__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_populate_id_map__SWIG_1___")]
  public static extern void run_metrics_populate_id_map__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_populate_id_map__SWIG_2___")]
  public static extern void run_metrics_populate_id_map__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_sort___")]
  public static extern void run_metrics_sort(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_clear___")]
  public static extern void run_metrics_clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_corrected_intensity_metric_set___")]
  public static extern void run_metrics_set_corrected_intensity_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_corrected_intensity_metric_set___")]
  public static extern global::System.IntPtr run_metrics_corrected_intensity_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_error_metric_set___")]
  public static extern void run_metrics_set_error_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_error_metric_set___")]
  public static extern global::System.IntPtr run_metrics_error_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_extraction_metric_set___")]
  public static extern void run_metrics_set_extraction_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_extraction_metric_set___")]
  public static extern global::System.IntPtr run_metrics_extraction_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_image_metric_set___")]
  public static extern void run_metrics_set_image_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_image_metric_set___")]
  public static extern global::System.IntPtr run_metrics_image_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_q_metric_set___")]
  public static extern void run_metrics_set_q_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_q_metric_set___")]
  public static extern global::System.IntPtr run_metrics_q_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_tile_metric_set___")]
  public static extern void run_metrics_set_tile_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_tile_metric_set___")]
  public static extern global::System.IntPtr run_metrics_tile_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_index_metric_set___")]
  public static extern void run_metrics_set_index_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_index_metric_set___")]
  public static extern global::System.IntPtr run_metrics_index_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_q_collapsed_metric_set___")]
  public static extern void run_metrics_set_q_collapsed_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_q_collapsed_metric_set___")]
  public static extern global::System.IntPtr run_metrics_q_collapsed_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_q_by_lane_metric_set___")]
  public static extern void run_metrics_set_q_by_lane_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_q_by_lane_metric_set___")]
  public static extern global::System.IntPtr run_metrics_q_by_lane_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_alignment_metric_set___")]
  public static extern void run_metrics_set_alignment_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_alignment_metric_set___")]
  public static extern global::System.IntPtr run_metrics_alignment_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_basecalling_metric_set___")]
  public static extern void run_metrics_set_basecalling_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_basecalling_metric_set___")]
  public static extern global::System.IntPtr run_metrics_basecalling_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_color_matrix_metric_set___")]
  public static extern void run_metrics_set_color_matrix_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_color_matrix_metric_set___")]
  public static extern global::System.IntPtr run_metrics_color_matrix_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_distortion_metric_set___")]
  public static extern void run_metrics_set_distortion_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_distortion_metric_set___")]
  public static extern global::System.IntPtr run_metrics_distortion_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_dynamic_phasing_metric_set___")]
  public static extern void run_metrics_set_dynamic_phasing_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_dynamic_phasing_metric_set___")]
  public static extern global::System.IntPtr run_metrics_dynamic_phasing_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_event_metric_set___")]
  public static extern void run_metrics_set_event_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_event_metric_set___")]
  public static extern global::System.IntPtr run_metrics_event_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_extended_tile_metric_set___")]
  public static extern void run_metrics_set_extended_tile_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_extended_tile_metric_set___")]
  public static extern global::System.IntPtr run_metrics_extended_tile_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_fwhm_grid_metric_set___")]
  public static extern void run_metrics_set_fwhm_grid_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_fwhm_grid_metric_set___")]
  public static extern global::System.IntPtr run_metrics_fwhm_grid_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_pf_grid_metric_set___")]
  public static extern void run_metrics_set_pf_grid_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_pf_grid_metric_set___")]
  public static extern global::System.IntPtr run_metrics_pf_grid_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_phasing_metric_set___")]
  public static extern void run_metrics_set_phasing_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_phasing_metric_set___")]
  public static extern global::System.IntPtr run_metrics_phasing_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_q_grid_metric_set___")]
  public static extern void run_metrics_set_q_grid_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_q_grid_metric_set___")]
  public static extern global::System.IntPtr run_metrics_q_grid_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_registration_metric_set___")]
  public static extern void run_metrics_set_registration_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_registration_metric_set___")]
  public static extern global::System.IntPtr run_metrics_registration_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_run_diagnostics_metric_set___")]
  public static extern void run_metrics_set_run_diagnostics_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_run_diagnostics_metric_set___")]
  public static extern global::System.IntPtr run_metrics_run_diagnostics_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_set_static_run_metric_set___")]
  public static extern void run_metrics_set_static_run_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_run_metrics_static_run_metric_set___")]
  public static extern global::System.IntPtr run_metrics_static_run_metric_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("c_csharp_run_metrics", EntryPoint="CSharp_IlluminafInterOpfRunMetrics_delete_run_metrics___")]
  public static extern void delete_run_metrics(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
