//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Illumina.InterOp.Metrics {

using System;
using System.Runtime.InteropServices;
using Illumina.InterOp.Run;

public class dynamic_phasing_metric : base_read_metric {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal dynamic_phasing_metric(global::System.IntPtr cPtr, bool cMemoryOwn) : base(c_csharp_metricsPINVOKE.dynamic_phasing_metric_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(dynamic_phasing_metric obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~dynamic_phasing_metric() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          c_csharp_metricsPINVOKE.delete_dynamic_phasing_metric(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public dynamic_phasing_metric() : this(c_csharp_metricsPINVOKE.new_dynamic_phasing_metric__SWIG_0(), true) {
  }

  public dynamic_phasing_metric(base_read_metric_header arg0) : this(c_csharp_metricsPINVOKE.new_dynamic_phasing_metric__SWIG_1(base_read_metric_header.getCPtr(arg0)), true) {
    if (c_csharp_metricsPINVOKE.SWIGPendingException.Pending) throw c_csharp_metricsPINVOKE.SWIGPendingException.Retrieve();
  }

  public dynamic_phasing_metric(uint lane, uint tile, uint read, float phasing_slope, float phasing_offset, float prephasing_slope, float prephasing_offset) : this(c_csharp_metricsPINVOKE.new_dynamic_phasing_metric__SWIG_2(lane, tile, read, phasing_slope, phasing_offset, prephasing_slope, prephasing_offset), true) {
  }

  public float phasing_slope() {
    float ret = c_csharp_metricsPINVOKE.dynamic_phasing_metric_phasing_slope(swigCPtr);
    return ret;
  }

  public float prephasing_slope() {
    float ret = c_csharp_metricsPINVOKE.dynamic_phasing_metric_prephasing_slope(swigCPtr);
    return ret;
  }

  public float phasing_offset() {
    float ret = c_csharp_metricsPINVOKE.dynamic_phasing_metric_phasing_offset(swigCPtr);
    return ret;
  }

  public float prephasing_offset() {
    float ret = c_csharp_metricsPINVOKE.dynamic_phasing_metric_prephasing_offset(swigCPtr);
    return ret;
  }

  public static string prefix() {
    string ret = c_csharp_metricsPINVOKE.dynamic_phasing_metric_prefix();
    return ret;
  }

  public static readonly int TYPE = c_csharp_metricsPINVOKE.dynamic_phasing_metric_TYPE_get();
  public static readonly int LATEST_VERSION = c_csharp_metricsPINVOKE.dynamic_phasing_metric_LATEST_VERSION_get();

}

}
