//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Illumina.InterOp.Table {

using System;
using System.Runtime.InteropServices;
using Illumina.InterOp.Metrics;
using Illumina.InterOp.Run;
using Illumina.InterOp.RunMetrics;

public class event_table : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal event_table(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(event_table obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~event_table() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          c_csharp_tablePINVOKE.delete_event_table(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public event_table() : this(c_csharp_tablePINVOKE.new_event_table(), true) {
  }

  public void set_data(uint rows, event_column_vector cols, ulong_vector data) {
    c_csharp_tablePINVOKE.event_table_set_data(swigCPtr, rows, event_column_vector.getCPtr(cols), ulong_vector.getCPtr(data));
    if (c_csharp_tablePINVOKE.SWIGPendingException.Pending) throw c_csharp_tablePINVOKE.SWIGPendingException.Retrieve();
  }

  public ulong at(uint r, event_column_id c) {
    ulong ret = c_csharp_tablePINVOKE.event_table_at(swigCPtr, r, (int)c);
    if (c_csharp_tablePINVOKE.SWIGPendingException.Pending) throw c_csharp_tablePINVOKE.SWIGPendingException.Retrieve();
    return ret;
    }

  public event_column_vector columns() {
    event_column_vector ret = new event_column_vector(c_csharp_tablePINVOKE.event_table_columns(swigCPtr), false);
    return ret;
  }

  public bool empty() {
    bool ret = c_csharp_tablePINVOKE.event_table_empty(swigCPtr);
    return ret;
  }

  public void clear() {
    c_csharp_tablePINVOKE.event_table_clear(swigCPtr);
  }

  public event_column column_at(uint col_index) {
    event_column ret = new event_column(c_csharp_tablePINVOKE.event_table_column_at(swigCPtr, col_index), false);
    if (c_csharp_tablePINVOKE.SWIGPendingException.Pending) throw c_csharp_tablePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint column_count() {
    uint ret = c_csharp_tablePINVOKE.event_table_column_count(swigCPtr);
    return ret;
  }

  public uint total_column_count() {
    uint ret = c_csharp_tablePINVOKE.event_table_total_column_count(swigCPtr);
    return ret;
  }

  public uint row_count() {
    uint ret = c_csharp_tablePINVOKE.event_table_row_count(swigCPtr);
    return ret;
  }

}

}
