//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Illumina.InterOp.Run {

public class image_dimensions : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal image_dimensions(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(image_dimensions obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~image_dimensions() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          c_csharp_runPINVOKE.delete_image_dimensions(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public image_dimensions(uint width, uint height) : this(c_csharp_runPINVOKE.new_image_dimensions__SWIG_0(width, height), true) {
  }

  public image_dimensions(uint width) : this(c_csharp_runPINVOKE.new_image_dimensions__SWIG_1(width), true) {
  }

  public image_dimensions() : this(c_csharp_runPINVOKE.new_image_dimensions__SWIG_2(), true) {
  }

  public uint width() {
    uint ret = c_csharp_runPINVOKE.image_dimensions_width(swigCPtr);
    return ret;
  }

  public uint height() {
    uint ret = c_csharp_runPINVOKE.image_dimensions_height(swigCPtr);
    return ret;
  }

}

}
