//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Illumina.InterOp.Metrics {

using System;
using System.Runtime.InteropServices;
using Illumina.InterOp.Run;

public class index_metric : base_read_metric {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal index_metric(global::System.IntPtr cPtr, bool cMemoryOwn) : base(c_csharp_metricsPINVOKE.index_metric_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(index_metric obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~index_metric() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          c_csharp_metricsPINVOKE.delete_index_metric(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public index_metric() : this(c_csharp_metricsPINVOKE.new_index_metric__SWIG_0(), true) {
  }

  public index_metric(index_metric_header arg0) : this(c_csharp_metricsPINVOKE.new_index_metric__SWIG_1(index_metric_header.getCPtr(arg0)), true) {
    if (c_csharp_metricsPINVOKE.SWIGPendingException.Pending) throw c_csharp_metricsPINVOKE.SWIGPendingException.Retrieve();
  }

  public index_metric(uint lane, uint tile, uint read, index_info_vector indices) : this(c_csharp_metricsPINVOKE.new_index_metric__SWIG_2(lane, tile, read, index_info_vector.getCPtr(indices)), true) {
    if (c_csharp_metricsPINVOKE.SWIGPendingException.Pending) throw c_csharp_metricsPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint size() {
    uint ret = c_csharp_metricsPINVOKE.index_metric_size(swigCPtr);
    return ret;
  }

  public index_info indices(uint n) {
    index_info ret = new index_info(c_csharp_metricsPINVOKE.index_metric_indices__SWIG_0(swigCPtr, n), false);
    if (c_csharp_metricsPINVOKE.SWIGPendingException.Pending) throw c_csharp_metricsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public index_info_vector indices() {
    index_info_vector ret = new index_info_vector(c_csharp_metricsPINVOKE.index_metric_indices__SWIG_1(swigCPtr), false);
    return ret;
  }

  public static string prefix() {
    string ret = c_csharp_metricsPINVOKE.index_metric_prefix();
    return ret;
  }

  public static readonly int TYPE = c_csharp_metricsPINVOKE.index_metric_TYPE_get();
  public static readonly int LATEST_VERSION = c_csharp_metricsPINVOKE.index_metric_LATEST_VERSION_get();

}

}
