//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Illumina.InterOp.Run {

public class invalid_tile_list_exception : global::System.ApplicationException {
    public invalid_tile_list_exception(string mesg) : base(mesg){}
    public invalid_tile_list_exception(string mesg, global::System.Exception inner) : base(mesg, inner){}

}

}
