//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Illumina.InterOp.Summary {

using System;
using System.Runtime.InteropServices;
using Illumina.InterOp.Metrics;
using Illumina.InterOp.Run;
using Illumina.InterOp.RunMetrics;

public class lane_summary : stat_summary {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal lane_summary(global::System.IntPtr cPtr, bool cMemoryOwn) : base(c_csharp_summaryPINVOKE.lane_summary_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(lane_summary obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~lane_summary() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          c_csharp_summaryPINVOKE.delete_lane_summary(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public lane_summary(uint lane, uint channel_count) : this(c_csharp_summaryPINVOKE.new_lane_summary__SWIG_0(lane, channel_count), true) {
  }

  public lane_summary(uint lane) : this(c_csharp_summaryPINVOKE.new_lane_summary__SWIG_1(lane), true) {
  }

  public lane_summary() : this(c_csharp_summaryPINVOKE.new_lane_summary__SWIG_2(), true) {
  }

  public surface_summary at(uint n) {
    surface_summary ret = new surface_summary(c_csharp_summaryPINVOKE.lane_summary_at(swigCPtr, n), false);
    if (c_csharp_summaryPINVOKE.SWIGPendingException.Pending) throw c_csharp_summaryPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void resize(uint n) {
    c_csharp_summaryPINVOKE.lane_summary_resize(swigCPtr, n);
  }

  public void lane(uint val) {
    c_csharp_summaryPINVOKE.lane_summary_lane__SWIG_0(swigCPtr, val);
  }

  public void tile_count(uint val) {
    c_csharp_summaryPINVOKE.lane_summary_tile_count__SWIG_0(swigCPtr, val);
  }

  public cycle_state_summary cycle_state() {
    cycle_state_summary ret = new cycle_state_summary(c_csharp_summaryPINVOKE.lane_summary_cycle_state(swigCPtr), false);
    return ret;
  }

  public uint lane() {
    uint ret = c_csharp_summaryPINVOKE.lane_summary_lane__SWIG_1(swigCPtr);
    return ret;
  }

  public uint tile_count() {
    uint ret = c_csharp_summaryPINVOKE.lane_summary_tile_count__SWIG_1(swigCPtr);
    return ret;
  }

  public uint size() {
    uint ret = c_csharp_summaryPINVOKE.lane_summary_size(swigCPtr);
    return ret;
  }

}

}
