//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Illumina.InterOp.Metrics {

using System;
using System.Runtime.InteropServices;
using Illumina.InterOp.Run;

public class q_collapsed_metric : base_cycle_metric {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal q_collapsed_metric(global::System.IntPtr cPtr, bool cMemoryOwn) : base(c_csharp_metricsPINVOKE.q_collapsed_metric_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(q_collapsed_metric obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~q_collapsed_metric() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          c_csharp_metricsPINVOKE.delete_q_collapsed_metric(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public q_collapsed_metric() : this(c_csharp_metricsPINVOKE.new_q_collapsed_metric__SWIG_0(), true) {
  }

  public q_collapsed_metric(q_collapsed_header arg0) : this(c_csharp_metricsPINVOKE.new_q_collapsed_metric__SWIG_1(q_collapsed_header.getCPtr(arg0)), true) {
    if (c_csharp_metricsPINVOKE.SWIGPendingException.Pending) throw c_csharp_metricsPINVOKE.SWIGPendingException.Retrieve();
  }

  public q_collapsed_metric(uint lane, uint tile, uint cycle, uint q20, uint q30, uint total, uint median_qscore) : this(c_csharp_metricsPINVOKE.new_q_collapsed_metric__SWIG_2(lane, tile, cycle, q20, q30, total, median_qscore), true) {
  }

  public uint q20() {
    uint ret = c_csharp_metricsPINVOKE.q_collapsed_metric_q20(swigCPtr);
    return ret;
  }

  public uint q30() {
    uint ret = c_csharp_metricsPINVOKE.q_collapsed_metric_q30(swigCPtr);
    return ret;
  }

  public uint total() {
    uint ret = c_csharp_metricsPINVOKE.q_collapsed_metric_total(swigCPtr);
    return ret;
  }

  public uint median_qscore() {
    uint ret = c_csharp_metricsPINVOKE.q_collapsed_metric_median_qscore(swigCPtr);
    return ret;
  }

  public float median_qscore_flt() {
    float ret = c_csharp_metricsPINVOKE.q_collapsed_metric_median_qscore_flt(swigCPtr);
    return ret;
  }

  public ulong cumulative_q20() {
    ulong ret = c_csharp_metricsPINVOKE.q_collapsed_metric_cumulative_q20(swigCPtr);
    return ret;
    }

  public ulong cumulative_q30() {
    ulong ret = c_csharp_metricsPINVOKE.q_collapsed_metric_cumulative_q30(swigCPtr);
    return ret;
    }

  public ulong cumulative_total() {
    ulong ret = c_csharp_metricsPINVOKE.q_collapsed_metric_cumulative_total(swigCPtr);
    return ret;
    }

  public float percent_over_q20() {
    float ret = c_csharp_metricsPINVOKE.q_collapsed_metric_percent_over_q20(swigCPtr);
    return ret;
  }

  public float percent_over_q30() {
    float ret = c_csharp_metricsPINVOKE.q_collapsed_metric_percent_over_q30(swigCPtr);
    return ret;
  }

  public float cumulative_percent_over_q20() {
    float ret = c_csharp_metricsPINVOKE.q_collapsed_metric_cumulative_percent_over_q20(swigCPtr);
    return ret;
  }

  public float cumulative_percent_over_q30() {
    float ret = c_csharp_metricsPINVOKE.q_collapsed_metric_cumulative_percent_over_q30(swigCPtr);
    return ret;
  }

  public void accumulate(q_collapsed_metric metric) {
    c_csharp_metricsPINVOKE.q_collapsed_metric_accumulate(swigCPtr, q_collapsed_metric.getCPtr(metric));
    if (c_csharp_metricsPINVOKE.SWIGPendingException.Pending) throw c_csharp_metricsPINVOKE.SWIGPendingException.Retrieve();
  }

  public static string prefix() {
    string ret = c_csharp_metricsPINVOKE.q_collapsed_metric_prefix();
    return ret;
  }

  public new static string suffix() {
    string ret = c_csharp_metricsPINVOKE.q_collapsed_metric_suffix();
    return ret;
  }

  public static readonly int TYPE = c_csharp_metricsPINVOKE.q_collapsed_metric_TYPE_get();
  public static readonly int LATEST_VERSION = c_csharp_metricsPINVOKE.q_collapsed_metric_LATEST_VERSION_get();

}

}
