//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Illumina.InterOp.Run {

public enum sub_tile_region_name {
  NNW,
  NNE,
  NW,
  NE,
  SW,
  SE,
  SSW,
  SSE,
  SubTileRegionCount,
  UnknownSubTileRegionName = 0x200
}

}
